auth/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'crowdfunding.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
)

crowdfunding/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'crowdfunding.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^$', 'project.views.home_page'),
    url(r'^auth/$', TemplateView.as_view(template_name="login.html")),
    url(r'^auth/register$', 'auth.views.register'),
    url(r'^auth/create_user$', 'auth.views.create_user'),
    url(r'^auth/login$', 'auth.views.__login'),
    url(r'^auth/logout$', 'auth.views._logout'),
    url(r'^auth/_login$', 'auth.views._login'),
    url(r'^project/$', 'project.views.show_project'),
    url(r'^project/show/(?P<id>[0-9]+)/$', 'project.views.show_project_page', name='show_project_page'),    
    url(r'^project/create$', 'project.views.create_project'),
    url(r'^project/update$', 'project.views.update_project'),
    url(r'^project/get_update_content$', 'project.views.get_update_content'),
    url(r'^project/save_project_update$', 'project.views.save_project_update'),
    url(r'^project/save_project$', 'project.views.save_project'),
    url(r'^project/pledge$', 'project.views.pledge'),
    url(r'^project/save_pledge$', 'project.views._pledge'),
    url(r'^project/update_pledge$', 'project.views.update_pledge'),
    url(r'^profile/(?P<uid>[0-9]+)$', 'auth.views.profile',name='profile'),
    url(r'', include('social_auth.urls')),
)

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
)

project/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import IntegerRangeField
# Create your models here.

class Project(models.Model):
	project_id=models.AutoField(primary_key=True)
	"""docstring for Project"""
	name=models.CharField(max_length=200)
	desc=models.CharField(max_length=400)
	money_req=IntegerRangeField(default=0,min_value=20000,max_value=200000)
	days_req=IntegerRangeField(default=0,min_value=7,max_value=60)
	#money_req=models.IntegerField(default=1)
	#days_req=models.IntegerField(default=1)
	photo=models.ImageField(upload_to='images/')
	video_link=models.URLField(max_length=1000)
	details=models.TextField(max_length=4000)
	project_use=models.CharField(max_length=100)
	risks_and_challenges=models.TextField(max_length=4000)
	#number_of_options=models.IntegerField(default=1)
	#pledge_value=models.TextField(max_length=1000)
	#pledge_reward=models.TextField(max_length=8000)
	date=models.DateTimeField(auto_now_add=True)
	user=models.ForeignKey(User)
	def __unicode__(self):
		return str(self.name)

class Pledger(models.Model):
	pid=models.AutoField(primary_key=True)
	pledger=models.ForeignKey(User,related_name='pledger_user_id')
	project=models.ForeignKey(Project,related_name='pledge_project_id')
	amount_pledged=models.IntegerField(default=0)
	def __unicode__(self):
		return str(self.pid)+' '+str(self.pledger)+' '+str(self.project)

class ProjectUpdate(models.Model):
	id=models.AutoField(primary_key=True)
	content = models.TextField(max_length = 4000)
	date = models.DateTimeField(auto_now_add = True)
	project_id = models.ForeignKey(Project)

	def __unicode__(self):
		return str(self.project_id)

project/forms.py
from django import forms
from django.forms import widgets
from django.forms import ModelForm
from project.models import Project,ProjectUpdate
from django.contrib.auth.models import User

class ProjectForm(ModelForm):
	
  class Meta:
    model = Project
    exclude = ("user",)
    number_of_options = forms.IntegerField(widget=forms.HiddenInput())
    pledge_value = forms.CharField(widget=forms.HiddenInput())
    pledge_reward = forms.CharField(widget=forms.HiddenInput())

class UpdateForm(ModelForm):

	class Meta:
		model = ProjectUpdate
		exclude = ("project_id",)

project/views.py
from django.shortcuts import render,render_to_response
from project.models import Project,Pledger,ProjectUpdate
from django.contrib import messages
from django.http import Http404,HttpResponseRedirect,HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.db.models import Sum
import datetime
from django.utils import timezone
from django.template import RequestContext
from django.core.urlresolvers import reverse
from project.forms import ProjectForm,UpdateForm
import json,re
# Create your views here.
def create_project(request):
	form = ProjectForm() # A empty, unbound form
	return render(request,'project/create.html',{'form':form},context_instance=RequestContext(request))

def category(request,id):
	if request.method=="POST":
		pass

def show_project_page(request,id):
	title=''
	current_page='projects'
	projects=Project.objects.filter(project_id=id).select_related()
	current_date=timezone.make_aware(datetime.datetime.now(),timezone.get_default_timezone())
	for item in projects:
		if item.user==request.user:
			item.is_uploader=True
		pledgers=Pledger.objects.filter(project_id=item.project_id).count()
		updates=ProjectUpdate.objects.filter(project_id=id).select_related()
		for update_item in updates:
			item.update=update_item.content
		item.backers=pledgers
		title=item.name #+str(' @ Crowd Fund | Lakshya Foundation')
		pledger=Pledger.objects.filter(project_id=item.project_id ).aggregate(Sum('amount_pledged'))
		item.backer=len(pledger)
		for key,value in pledger.iteritems():
			if not value is None:
				item.percent=int(100*(float(value)/float(item.money_req)))
				item.amount_pledged=value
			else:
				item.percent=0
				item.amount_pledged=0
		diff=current_date-item.date
		if item.days_req-diff.days>0:
			item.days_left=item.days_req-diff.days
		else:
			item.days_elapsed=diff.days-item.days_req
		# decoded_pledge_values=json.loads(item.pledge_value)
		# decoded_pledge_rewards=json.loads(item.pledge_reward)
		# item.pledge_values=decoded_pledge_values
		# item.pledge_rewards=decoded_pledge_rewards
		# item.pledge=zip(item.pledge_values,item.pledge_rewards)
		pledgers=Pledger.objects.filter(project_id=item.project_id)
		for row in pledgers:
			if row.pledger==request.user:
				item.is_pledger=True
	return render(request,'project/projectpage.html',{'project':projects,'title':title,'current_page':current_page})

def show_project(request):
	title='Projects'
	current_page='projects'
	current_date=timezone.make_aware(datetime.datetime.now(),timezone.get_default_timezone())
	projects=Project.objects.all().select_related()
	for item in projects:
		pledger=Pledger.objects.filter(project_id=item.project_id ).aggregate(Sum('amount_pledged'))
		for key,value in pledger.iteritems():
			if not value is None:
				item.percent=int(100*(float(value)/float(item.money_req)))
				item.amount_pledged=value
			else:
				item.percent=0
				item.amount_pledged=0
		diff=current_date-item.date
		if item.days_req-diff.days>0:
			item.days_left=item.days_req-diff.days
		else:
			item.days_elapsed=diff.days-item.days_req
	category=Project.objects.values_list('project_use', flat=True).distinct()
	return render(request,'project/project_1.html',{'title':title,'current_page':current_page,'project':projects,'category':category})

def pledge(request):
	if request.method=="POST":
		amount=int(request.POST.get('amount',False))
		proj_id=int(request.POST.get('pid',False))
		pledger_id=int(request.POST.get('uid',False))
		pledge=Pledger.objects.pledge(pledger_id,proj_id,amount)
		pledge.save()
		messages.info(request,'Your pledge has been recorded')
		return HttpResponseRedirect('/project')

def save_project(request,**kwargs):
	if request.method == 'POST':
		user=request.user
		form = ProjectForm(request.POST, request.FILES)
		print form.is_valid()
		print form.errors
    	if form.is_valid():
    		project=form.save(commit=False)
    		project.user=user
    		link=project.video_link
    		video_code=re.findall(r'v\=([\-\w]+)', link )[0]
    		project.video_link="//www.youtube.com/v/"+str(video_code)
    		project.save()
    		messages.info(request,'Project has been successfully created')
    		return HttpResponseRedirect('/project')
    	else:
         	raise Http404

def _pledge(request):
	if request.method=="POST":
		proj_id=int(request.POST.get('pid',False))
		amount=int(request.POST.get('amount',False))
		proj=Project.objects.filter(project_id=proj_id)
		project=Project()
		for item in proj:
			project=item
		pledge=Pledger()
		pledge.pledger=request.user
		pledge.project=project
		pledge.amount_pledged=amount
		pledge.save()
		messages.info(request,'Your pledge has been recorded')
		return HttpResponseRedirect('/project/show/'+str(proj_id))

def update_pledge(request):
	if request.method == "POST":
		proj_id=int(request.POST.get('pid',False))
		amount = int(request.POST.get('amount',False))
		proj = Project.objects.filter(project_id=proj_id)
		project = Project()
		for item in proj:
			project=item
		pledge = Pledger()
		pled = Pledger.objects.filter(project=project,pledger=request.user)
		for item in pled:
			pledge = item
		pledge.amount_pledged = amount;
		pledge.save()
		messages.info(request,'Your pledge has been updated')
		return HttpResponseRedirect('/project/show/'+str(proj_id))

def update_project(request):
	projects=Project.objects.filter(user=request.user)
	return render(request,"project/project_updates.html",{'projects':projects})
def get_update_content(request):
	if request.method=="POST":
		pid=request.POST.get('proj')
		updates=ProjectUpdate.objects.filter(project_id=pid).select_related()
		print pid
		content=""
		for update in updates:
			content=update.content
		response_data = {}
		response_data['result'] = content
		response_data['message'] = "right in the eye"
		return HttpResponse(json.dumps(response_data), content_type="application/json")
	else:
		print "not post"

def save_project_update(request):
	if request.method=="POST":
		content = request.POST.get('content')
		pid = request.POST.get('project')

		proj = Project.objects.filter(project_id=pid).select_related()
		project=Project()
		for item in proj:
			project=item
		check_project_update=ProjectUpdate.objects.filter(project_id=project)
		update=ProjectUpdate()
		if check_project_update:
			for item in check_project_update:
				update=item
			update.content=content
			update.save()
			messages.info(request,'Project Update has been successfully added')
		else:
			update.content=content
			update.project_id=project
			update.save()
			messages.info(request,'Project Update has been successfully added')
    	return HttpResponseRedirect('/project')

def home_page (request):
	title='Index'
	current_page='index'
	current_date=timezone.make_aware(datetime.datetime.now(),timezone.get_default_timezone())
	projects=Project.objects.all().select_related()
	for item in projects:
		pledger=Pledger.objects.filter(project_id=item.project_id ).aggregate(Sum('amount_pledged'))
		for key,value in pledger.iteritems():
			if not value is None:
				item.percent=int(100*(float(value)/float(item.money_req)))
				item.amount_pledged=value
			else:
				item.percent=0
				item.amount_pledged=0
		diff=current_date-item.date
		if item.days_req-diff.days>0:
			item.days_left=item.days_req-diff.days
		else:
			item.days_elapsed=diff.days-item.days_req
	category=Project.objects.values_list('project_use', flat=True).distinct()
	return render(request,'index.html',{'title':title,'current_page':current_page,'project':projects,'category':category})

crowdfunding/templates/project/create.html
{%extends "project/header.html"%}{%block content%} {%load css_filter%}

<!--link rel="stylesheet" href="{{STATIC_URL}}css/style.css">
<link rel="stylesheet" href="{{STATIC_URL}}css/animate.min.css">
<link rel="stylesheet" href="{{STATIC_URL}}css/font-awesome.min.css"-->
<!--[if lt IE 9]>
    <script src="{{STATIC_URL}}js/html5shiv.js"></script>
    <script src="{{STATIC_URL}}js/respond.min.js"></script>
    <![endif]-->

<div class="container-fluid">

    <div class="row">
        {%if user.is_authenticated %} {%if messages %}{% for message in messages %}
        <div class="container-fluid">
            <div class="alert alert-{{message.tags}} fade in" style="text-align:center;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message|safe }}
            </div>
        </div>{% endfor %}{% endif %}

        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <form class="form-horizontal well" method="POST" action="{{BASE_URL}}/project/save_project" enctype="multipart/form-data" id="project_form">{% csrf_token %}

                <section><h1 style="text-align: center;">Create Project</h1></section>
                
               <br/> 
                <p>{{ form.non_field_errors }}</p>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="project_name">Project Name</label>
                    <div class="controls">
                        {{form.name|addClass:'form-control input-md'}}
                    </div>
                </div>
                <!-- Textarea -->

                <div class="form-group">
                    <label class="control-label" for="project_desc">One Line Project Description</label>
                    <div class="controls">
                        {{form.desc|addClass:'form-control input-md'}}
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="money_req">Money Required</label>
                    <div class="controls">
                        {{form.money_req|addClass:'form-control input-md'}}
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="days_req">Days required</label>
                    <div class="controls">
                        {{form.days_req|addClass:'form-control input-md'}}
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="img_link">Upload image:</label>
                    <div class="controls">
                        {{form.photo|addClass:'btn btn-md btn-primary'}}
                    </div>
                </div>
                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="video_link">Link to video:</label>
                    <div class="controls">
                        {{form.video_link|addClass:'form-control input-md'}}
                    </div>
                </div>

                <!-- Textarea -->
                <div class="form-group">
                    <label class="control-label" for="details">Detailed Explanation:</label>
                    <div class="controls">
                        {{form.details|addClass:'form-control input-md'}}
                    </div>
                </div>

                <!-- Textarea -->
                <div class="form-group">
                    <label class="control-label" for="risks_and_challenges">Risks and Challenges:</label>
                    <div class="controls">
                        {{form.risks_and_challenges|addClass:'form-control input-md'}}
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="control-label" for="project_use">Project Use:</label>
                    <div class="controls">
                        {{form.project_use|addClass:'form-control input-md'}}
                    </div>
                </div>
                <!-- <div class="form-group">
                    <label for="" class="control-label">Number of options</label>
                    <div class="controls">
                        <select name="num_of_options" id="num_of_options" onchange="change(this);">
                            <option value="-1">Select number</option>
                            {%for i in "xxxxx"%}
                            <option value="{{forloop.counter}}">{{forloop.counter}}</option>{%endfor%}
                        </select>
                    </div>
                </div> -->
               <!--  <input type="hidden" name="number_of_options" id="number_of_options">
                <input type="hidden" name="pledge_value" id="pledge_value">
                <input type="hidden" name="pledge_reward" id="pledge_reward">
                <!-- Look at the script bro ->
                <div id="pledge_options" style="display:none;">
                
                </div> -->
                <!-- End of pledging and swearing -->
                <!-- Button -->
                <div class="form-group">
                    <label class="control-label" for="submit"></label>
                    <div class="controls">
                        <input type="button" id="btnSubmit" name="btnSubmit" class="btn btn-success" value="Submit" onclick="submit();">
                    </div>
                </div>

                </fieldset>
            </form>
        </div>
        <script>
        // function change(item) {
        //     var k = item;
        //     var len = ~~(k.value);
        //     var cont = "";
        //     $('#pledge_options').html("");
        //     for (var i = 0; i < len; i++) {
        //         cont += "<div class='form-group'>";
        //         cont += "<label class='control-label'>Pledge " + (i + 1) + "</label>";
        //         cont += "<div class='controls'><input class='form-control input-md' type='text' id='pledge" + (i + 1) + "' name='pledge"+(i+1)+"'/></div>";
        //         cont += "<label class='control-label'>Reward " + (i + 1) + "</label>";
        //         cont +="<div class='controls'><input class='form-control input-md' type='text' id='reward"+(i+1)+"'name='reward"+(i+1)+"'/></div>";
        //         cont += "</div>";
        //     };
        //     $('#pledge_options').append(cont);
        //     $('#pledge_options').show();
        // }
        function form_submit(){
            var t=document.getElementById('project_form');
            document.getElementById('project_form').submit();
        }
         
        </script> 
        {%else%}
        <div class="jumbotron">
            <p class="lead">You must be logged in to create a project.</p>
        </div>
        {%endif%}
    </div>
</div>
{% endblock %}

crowdfunding/templates/project/header.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta name="author" content="">
  <link rel="shortcut icon" href="{{STATIC_URL}}ico/favicon.ico">
  <title>{{title}}</title>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,600">
  <script src="{{STATIC_URL}}js/jquery.min.js"></script>
  <script src="{{STATIC_URL}}modernizr.js" type="text/javascript"></script>
  <link rel="stylesheet" href="{{STATIC_URL}}css/font_awesome.min.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/animate.min.css">
  <!--link rel="stylesheet" href="{{STATIC_URL}}css/kickstarter.css"-->
  <link rel="stylesheet" href="{{STATIC_URL}}css/project-post.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/bootstrap.min.css">
  <link href="{{STATIC_URL}}style.css" media="all" rel="stylesheet" type="text/css" />


  
</head>
<body>
<!-- Header Nav bar starts here -->
   <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{BASE_URL}}"><img src="{{STATIC_URL}}logolakshya.png" alt="Lakshya Foundation" width="auto" height="100%" />Crowd Funding</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav pull-right">
            <!--li ><a href="#">Home</a></li-->
            <!--li {% if current_page == "projects" %}class="active"{% endif %}--> 
            <li><a href="{{BASE_URL}}/project" >Explore Projects</a></li>
            <!--li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li-->
            {% if user.is_authenticated %}
            <li><a href="{{BASE_URL}}/project/create">Start New Project</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">My Profile</a></li>
                <li><a href="#">Projects Created</a></li>
                <li><a href="#">Projects Backed</a></li>
                <li><a href="#">Change Password</a></li>
                <li><a href="{{BASE_URL}}/auth/logout">Logout</a></li>
              </ul>
            </li>
                {% else %}
                <li><a href="{{BASE_URL}}/auth/login">Login</a></li>
                {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    {%if messages%}
    {% for message in messages%}
    <div class="container">
      <div class="alert alert-success fade in" style="text-align:center;">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true" onclick="$('.alert').hide()">&times;</button>
        {{message}}
      </div>
    </div>
  {% endfor %}
  {%endif%}

<!-- Header Nav bar ends here -->

<!-- Content for all pages comes here -->
<div id="wrap">
{% block content %}
{% endblock %}
</div>
<div id="push"></div>

<!-- End page content -->

<!-- Footer section starts here-->
  <div class="container-fluid panel-footer">
    <div class="row custom-footer">
      <div class="col-md-4">
        <p><a href="#">Explore Projects</a></p>
        <p><a href="#">About</a></p>
        <p><a href="#">Contact</a></p>
        <p><a href="#">Lakshya Foundation</a></p>
      </div>

      <div class="col-md-4">
        <p><a href="#">How this works</a></p>
        <p><a href="#">What is the aim</a></p>
        <p><a href="#">Who benefits</a></p>
        <p><a href="#">More FAQs</a></p>
      </div>

      <div class="col-md-4">
        
        <!-- Begin MailChimp Signup Form -->
            <div id="mc_embed_signup">
            <form action="//thelakshyafoundation.us3.list-manage.com/subscribe/post?u=273367d87612b051254836e04&amp;id=6a26243903" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <div id="mc_embed_signup_scroll">
                  <label for="mce-EMAIL">Want to know about the cool stuff happening here? Let the updates come to you!</label>
                  <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;"><input type="text" name="b_273367d87612b051254836e04_6a26243903" tabindex="-1" value=""></div>
                    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                </div>
            </form>
            </div>
            <!--End mc_embed_signup-->

      </div>
    </div>

    <div class="row">
      <div class="text-muted col-md-12 copyright"> Copyright &#169; 
        <script type="text/javascript">var d = new Date();document.write(d.getFullYear());</script> 
        | All Rights Reserved | The Lakshya Foundation </div>
  </div>
<!-- Footer section ends here -->
  <script src="{{STATIC_URL}}application.js" type="text/javascript"></script>
  <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>

</body>
</html>

crowdfunding/templates/project/list.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Minimal Django File Upload Example</title>	
	</head>

	<body>
		<!-- List of uploaded documents -->
		{% if documents %}
			<ul>
			{% for document in documents %}
				<li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No documents.</p>
		{% endif %}

		<!-- Upload form. Note enctype attribute! -->
		<form action="{% url "list" %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<p>{{ form.non_field_errors }}</p>
			<p>{{ form.docFile.label_tag }} {{ form.docFile.help_text }}</p>
			<p>
				{{ form.docFile.errors }}
				{{form.title}}
				{{ form.docFile }}
			</p>
			<p><input type="submit" value="Upload" /></p>
		</form>
		
	</body>

</html> 

crowdfunding/templates/project/project_updates.html
{%extends "project/header.html"%} {%block content%}
<link rel="stylesheet" href="{{STATIC_URL}}css/style.css">
<link rel="stylesheet" href="{{STATIC_URL}}css/animate.min.css">
<link rel="stylesheet" href="{{STATIC_URL}}css/font-awesome.min.css">

<div class="container">
	<div class="row">
	<center>
		<legend>Project update</legend>		
	</center>
	<form class="form-horizontal" action="{{BASE_URL}}/project/save_project_update" method="POST">{%csrf_token%}
		<div class="form-group">
		<label for="" class="control-label">Project:</label>
			<select name="project" id="id_project">
				<option value="-1">Select project</option>
				{%for item in projects%}<option value="{{item.project_id}}">{{item.name}}</option>{%endfor%}
			</select>
		</div>
		<div class="form-group">
			<label for="" class="control-label">Update:</label>
			<div class="controls">
			<textarea name="content" id="id_content" cols="30" rows="10" class="form-control"></textarea>
			</div>
		</div>
		<div class="form-group">
			<input type="submit" class="btn btn-warning btn-md" value="Submit">
		</div>
	</form>
	</div>
</div>
<script>
$(document).ready(function(){
	$('#id_project').change(function () {
		$.post(
			"{{BASE_URL}}/project/get_update_content",
    		{
      			proj:$(this).val(),
      			csrfmiddlewaretoken:$("input[name=csrfmiddlewaretoken]").val()
    		},
    		function(data,status){
    			$('#id_content').val(data.result);
    			if(data.result=="" && $(this).val()>0){
    				alert("No updates have been made. Continue adding your update");
    			}
      			// alert("Data: " + data.message + "\nStatus: " + status);
    		});
	});
});
</script>
{%endblock%}